services:
  # jaeger:
  #   container_name: jaeger
  #   image: jaegertracing/all-in-one:1.62.0
  #   ports:
  #     - '16686:16686'
  #   networks:
  #     - sidecar

  # datadog-agent:
  #   container_name: datadog-agent
  #   image: datadog/agent:7.58.0
  #   environment:
  #     DD_API_KEY: ''
  #     DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: '0.0.0.0:4318'
  #     DD_SITE: ''
  #   ports:
  #     - '4318:4318'
  #   networks:
  #     - sidecar
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /proc/:/host/proc/:ro
  #     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - '9000:9000'
      - '8123:8123'
    networks:
      - sidecar

  otelcol:
    container_name: otelcol
    image: wesha/otel-clickhouse:0.4.0
    restart: on-failure:10
    networks:
      - sidecar

  python:
    container_name: python
    build:
      dockerfile: ./python/Dockerfile
    ports:
      - '4000:4000'
    networks:
      - sidecar
  python-sidecar:
    container_name: python-sidecar
    command: sidecar
    image: wesha/sidecar:0.15.3-rc.10
    restart: on-failure:10
    environment:
      NAMESPACE: 'python'
      NAME: 'python-sidecar'
      VERSION: '0.1.0-alpha.0'
      HTTP_ADDRESS: ':3501'
      GRPC_ADDRESS: ':50001'
      SERVICE_NAME: 'localhost'
      SERVICE_PORT: '4000'
      SERVICE_PROTOCOL: 'http'
      STORE: 'memory'
      BROKER: 'snssqs'
      BROKER_ADDRESS: 'https://sqs.us-west-2.amazonaws.com'
      CONSUMERS: 'python-neworder'
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
    network_mode: 'service:python'

  node:
    container_name: node
    build:
      dockerfile: ./node/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - sidecar
  node-sidecar:
    container_name: node-sidecar
    command: sidecar
    image: wesha/sidecar:0.15.3-rc.10
    restart: on-failure:10
    environment:
      NAMESPACE: 'node'
      NAME: 'node-sidecar'
      VERSION: '0.1.0-alpha.0'
      HTTP_ADDRESS: ':3501'
      GRPC_ADDRESS: ':50001'
      SERVICE_NAME: 'localhost'
      SERVICE_PORT: '3000'
      SERVICE_PROTOCOL: 'http'
      STORE: 'memory'
      STORES: 'orders'
      BROKER: 'snssqs'
      BROKER_ADDRESS: 'https://sqs.us-west-2.amazonaws.com'
      CONSUMERS: 'node-neworder,node-b'
      SECRET: 'ssm'
      SECRET_ADDRESS: 'https://ssm.us-west-2.amazonaws.com'
      SECRET_PREFIX: '/node/'
      TRACE_EXPORTER: 'otelp'
      TRACE_ADDRESS: 'otelcol:4317'
      TRACE_PROTOCOL: 'grpc'
      # TRACE_SECURE: '1'
      # TRACE_HEADERS: 'x-honeycomb-team='
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
    network_mode: 'service:node'

  react:
    container_name: react
    build:
      dockerfile: ./react/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - sidecar
  react-sidecar:
    container_name: react-sidecar
    command: sidecar
    image: wesha/sidecar:0.15.3-rc.10
    restart: on-failure:10
    environment:
      NAMESPACE: 'react'
      NAME: 'react-sidecar'
      VERSION: '0.1.0-alpha.0'
      HTTP_ADDRESS: ':3501'
      GRPC_ADDRESS: ':50001'
      SERVICE_NAME: 'localhost'
      SERVICE_PORT: '8080'
      SERVICE_PROTOCOL: 'http'
      STORE: 'memory'
      BROKER: 'snssqs'
      BROKER_ADDRESS: 'https://sns.us-west-2.amazonaws.com'
      PRODUCERS: 'arn:aws:sns:us-west-2:339936612855:neworder,arn:aws:sns:us-west-2:339936612855:b'
      TRACE_EXPORTER: 'otelp'
      TRACE_ADDRESS: 'otelcol:4317'
      TRACE_PROTOCOL: 'grpc'
      # TRACE_SECURE: '1'
      # TRACE_HEADERS: 'x-honeycomb-team='
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
    network_mode: 'service:react'

networks:
  sidecar:
